# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'iosdemo' do
    
    pod 'Appodeal', '~> 0.8.1' # for XCODE 7
#   pod 'Appodeal', '0.4.8' # for XCODE 6.4

    pod 'MWFeedParser', '~> 1.0'

end
